services:

  app:
    image: khoivan193/simple-cicd-demo:latest
    ports:
      - "8888:80"

    environment:
      DB_HOST: db
      DB_NAME: demo
      DB_USER: demo
      DB_PASS: demo123

    depends_on:
      - db

  db:
    image: mariadb:11

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo123

    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
